### ISSUE TITLE
Copper rod recipe conflicts with lightning rod recipe.

### ISSUE THREAD

**Issue by Jamalam360** [woodiertexas/architecture-extensions#11]
### Describe the bug

As said in the title, the recipe for the copper rod is the same as for the lightning rod, making lightning rods uncraftable.

### Which side have you encountered the bug on?

Both

### Steps to reproduce

Self-explanatory.

**Comment by woodiertexas** [comment]
This should be fixed in Arch-Ex v1.0.0+1.18.2 and v2.0.0+1.19 when those versions are released.
