### ISSUE TITLE
Block of iron recipe conflict

### ISSUE THREAD

**Issue by VictorKoenders** [woodiertexas/architecture-extensions#12]
### Describe the bug

When trying to turn blocks of iron back into 9 iron ingots, instead 32 iron rods show up. This makes it impossible to get iron ingots out of blocks of iron.

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Put block of iron in crafting grid
2. Expect 9 iron ingots
3. Get 32 iron rods instead

![image](https://user-images.githubusercontent.com/2743142/176834696-c6782e5d-ab11-4f42-b21a-276db3d7da1f.png)

**Comment by woodiertexas** [comment]
This bug has been fixed in v1.0.1 of Architecture Extensions.

https://modrinth.com/mod/arch-ex/version/1.0.1%2B1.19
https://modrinth.com/mod/arch-ex/version/1.0.1%2B1.18.2

**Comment by VictorKoenders** [comment]
Thanks!
