### ISSUE TITLE
[Suggestion] Sideways versions of vanilla block shapes

### ISSUE THREAD

**Issue by Cart3r1234** [woodiertexas/architecture-extensions#2]
Sideways Stairs, walls, and (gasp!) Slabs would make for interesting decoration blocks.  Sideways fences and glass panes too perhaps, although getting the connections right may cause issues

**Comment by woodiertexas** [comment]
Sideway stairs might be able to piggyback off the circle corner block I was playing around with. Horizontal walls might be difficult to implement though. Vertical slabs is something I've seen plenty of people want in Minecraft.

Horizontal fences would probably operate like horizontal walls. Horizontal glass panes may be easy to implement.

**Comment by woodiertexas** [comment]
Regarding slabs, this mod should satisfy that: https://modrinth.com/mod/autoslabs
