### ISSUE TITLE
Powdered / sand blocks added

### ISSUE THREAD

**Issue by Fusion-Flux** [woodiertexas/architecture-extensions#41]
### List the features you want added to Arch-Ex.

what the title says
powdered concrete and sand as arch ex blocks
and possibly the sandstone top for a facade? and other sandstone varients for arch ex blocks

### Describe how your feature(s) will work if applicable.

n/a

### Additional context

sorry i should have seen this gap last night

**Comment by woodiertexas** [comment]
Was added in [Arch-Ex v3.4.0](https://modrinth.com/mod/arch-ex/version/3.4.0+1.20.1)
