### ISSUE TITLE
An alternative way of translating the names of items does not work

### ISSUE THREAD

**Issue by aratakileo** [woodiertexas/architecture-extensions#48]
### Describe the bug

I have embedded the following translation into the mod file:
[ru_ru.zip](https://github.com/DebuggyTeam/architecture-extensions/files/12279468/ru_ru.zip)

The original translation method works, but the alternative one doesn't. In this case, I used the key `block.architecture_extensions.minecraft.stone_round_arch`, but it had no effect.
![image](https://github.com/DebuggyTeam/architecture-extensions/assets/83653555/1ec3288a-1f81-4b38-9b3a-a7504e5db623)
![image](https://github.com/DebuggyTeam/architecture-extensions/assets/83653555/70028a39-0425-43d2-b80c-3fa0fd20f1bc)

[modificated by me version of mod architecture_extensions-3.3.0+1.20.1.zip](https://github.com/DebuggyTeam/architecture-extensions/files/12279525/architecture_extensions-3.3.0%2B1.20.1.zip)

### Which side have you encountered the bug on?

Client

### Additional context

mod version: `v3.3.0+1.20.1`

**Comment by woodiertexas** [comment]
I believe this has been fixed in [3.4.0 of Arch-Ex](https://modrinth.com/mod/arch-ex/version/3.4.0+1.20.1)

**Comment by aratakileo** [comment]
That would be nice

**Comment by falkreon** [comment]
The included ru_ru file really helped locate the problem! I have a fix incoming.

**Comment by aratakileo** [comment]
Good to know
