### ISSUE TITLE
Panel Block Concepts

### ISSUE THREAD

**Issue by acikek** [woodiertexas/architecture-extensions#5]
### List the blocks you want added to AE.

- Sheet Metal
  - Normal and rusted variants
- Ceramic wall tiles

### List the blocktype(s) you want added to AE.

- Walling / Panel block

### What blocktypes do your block(s) fall under if applicable.

- [ ] Column Block
- [ ] Arch Block
- [ ] Post Block

### Describe how your blocktype(s) will work if applicable.

The panel blocks are vertical 1-voxel thick tiles (similar to carpets). They can be placed on their own without any support. Since it's not a full block, perhaps some special rules could be applied concerning placement. For example, it wouldn't make sense to have a room's walls be decorated with tiles but not being able to place anything in that block space. Additionally, if panel blocks are placed backwards instead of to decorate an existing wall - i.e., they become the wall - then nothing can be placed on the room's external walls. I imagine this needs a lot of thought and some rendering trickery to work well.

**Comment by woodiertexas** [comment]
While sheet metal and ceramic tile blocks are a great idea... The amount work to implement them and get them working well would be a lot. It would probably require a whole new API/library mod in the vein of the multipart libs to let players be able to place stuff in the "blockspace" of a panel blocktype.

**Comment by woodiertexas** [comment]
So this is largely implemented in #23 aside from sheet metal.
