### ISSUE TITLE
Axe mining speed as slow as hand breaking blocks

### ISSUE THREAD

**Issue by texaswriter** [woodiertexas/architecture-extensions#53]
### Describe the bug

After several hours of trial/error through removing/adding mods, I finally found the culprit, though I am not sure why this mod causes this problem:

Axe mining speed is as slow as hand breaking blocks regardless of axe tier (iron, gold, etc.) or enchantments (efficiency...). 

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Install mod (using a homebrewed Quilt modpack on 1.19.2), using (architecture_extensions-1.1.3+1.19.jar). Using 0.19.2 Quilt Loader (but was having the same issue with other versions) 
2. Create world
3. Craft axe or give with cheats
4. Attempt to mine a log... very slow 
...

### Additional context

MOD LIST: 
AdditionalBanners-Fabric-1.19.2-10.1.7.jar
additionallanterns-1.1.1-fabric-mc1.19.2.jar
advdebug-2.3.0.jar
AE2WTLib-12.9.5.jar
AmbientEnvironment-fabric-1.19.2-8.0+3.jar
animatica-0.5+1.19.jar
another_furniture-fabric-1.19.2-2.1.4.jar
apathy-fabric-1.19.2-2.6.jar
appleskin-fabric-mc1.19-2.4.1.jar
appliedenergistics2-fabric-12.9.6.jar
architects-palette-fabric-3.0.0.jar
architectury-6.5.85-fabric.jar
badpackets-fabric-0.2.1.jar
balm-fabric-1.19.2-4.5.7.jar
bedrockwaters-1.7.3+1.19.2.jar
better-end-sky-0.1.1.jar
Bookshelf-Fabric-1.19.2-16.3.20.jar
boring_default_game_rules-1.0.4+1.19.2.jar
BotanyPots-Fabric-1.19.2-9.0.33.jar
BotanyTrees-Fabric-1.19.2-5.0.8.jar
BuildingWands-mc1.19.2-2.6.8-release-fabric.jar
cardinalboats_1.19_1.2.3.jar
carpet-extra-1.19.2-1.4.84.jar
carpet-fixes-1.19-1.12.2.jar
cccbridge-mc1.19.2-fabric-v1.5.1.jar
cc-restitched-1.101.2.jar
charmonium-fabric-1.19.2-4.2.1.jar
chickensshed-1.19.x-1.3.6.jar
chipped-fabric-1.19.2-2.1.5.jar
chunksfadein-v3.0.11-1.19.jar
CITResewn-1.1.2+1.19.2.jar
cleancut-1.19.2-5.1-fabric.jar
clienttweaks-fabric-1.19.2-8.1.2.jar
cloth-config-8.2.88-fabric.jar
ColorfulAzaleas-fabric-1.19.2-2.3.1.jar
colormatic-3.1.2+mc.1.19.jar
compact_storage_fabric-5.0.3_1.19.2.jar
compressed-1.19.2-1.8.0.jar
continuity-2.0.2+1.19.jar
CorgiLib-fabric-1.19.2-1.0.0.34.jar
Couplings-1.9.1+1.19.jar
coyote_time-1.0.0.jar
create-fabric-0.5.1-b-build.1089+mc1.19.2.jar
crowmap-1.19-1.0.1.jar
crunchy_crunchy_advancements-1.3.1+1.19.jar
DarkPaintings-Fabric-1.19.2-13.1.5.jar
diamold-1.5.0.jar
Display Case-quilt-1.19-1.0.7.jar'
drogstyle-1.0.0+1.19.jar
DyeableFishingLines-1.0.1.jar
dynamic-fps-2.2.0.jar
ears-fabric-1.19-1.4.6.jar
easierenchanting-1.5.0.jar
elytraslot-fabric-6.1.1+1.19.2.jar
emi-1.0.2+1.19.2+fabric.jar
EMITrades-fabric-1.0.2+mc1.19.2.jar
enhanced_attack_indicator-1.0.4+1.19.jar
enhancedblockentities-0.7.2+1.19.2.jar
everycomp-1.19.2-2.5.1-fabric.jar
exordium-fabric-1.0.2-mc1.19.2-hotfix.jar
ExtendedDrawers-1.4.3+mc.1.19.2.jar
fabrication-3.2.7+1.19.jar
fabric-carpet-1.19.2-1.4.84+v221018.jar
FabricShieldLib-1.6.1-1.19.jar
fabrictailor-2.0.1.jar
fabric-title-changer-1.0.7.jar
fallingleaves-1.13.0+1.19.2.jar
fastopenlinksandfolders-1.1.1.jar
fat-experience-orbs-2.0.1+1.18-quilt.jar
feed-the-bees-1.2.2+1.19.jar
ferritecore-5.0.3-fabric.jar
Fishingreal-1.19.2-1.6.jar
ftb-chunks-fabric-1902.4.1-build.290.jar
ftb-library-fabric-1902.4.1-build.236.jar
ftb-quests-fabric-1902.5.3-build.258.jar
ftb-teams-fabric-1902.2.14-build.123.jar
geckolib-quilt-1.19-3.1.40.jar
HorseBuff-1.19-2.0.1.jar
idwtialsimmoedm-0.2.0+1.19.jar
illuminations-1.10.8.jar
ImmediatelyFast-1.1.12+1.19.jar
immersive_paintings-0.6.5+1.19.2-fabric.jar
indium-1.0.9+mc1.19.2.jar
inspecio-1.6.0+1.19.jar
inventorytabs-0.6.2+1.19.x.jar
iris-mc1.19.2-1.6.4.jar
item-filters-fabric-1902.2.9-build.51.jar
item-model-fix-1.0.3+1.19.jar
jamlib-0.6.0+1.19.jar
kaffees_dual_ride-1.1.0.jar
keep-my-hand-1.0.0.jar
Kiwi-1.19.1-fabric-8.3.3.jar
krypton-0.2.1.jar
lambdabettergrass-1.3.0+1.19.jar
lambdynamiclights-2.2.0+1.19.2.jar
lazydfu-0.1.3.jar
leaves-us-in-peace-1.0.12+MC1.19-1.19.2.jar
lilwings-fabric-1.19.2-1.2.3.jar
lithium-fabric-mc1.19.2-0.11.1.jar
loadingscreentips-1.1.0.jar
lucium-1.5-pre1.jar
LunaSlimes-1.6-1.19.2.jar
main-menu-credits-1.1.1.jar
mcw-bridges-2.1.0-mc1.19.2fabric.jar
mcw-doors-1.1.0fabric-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2fabric.jar
mcwifipnp-1.6.2-1.19.2-quilt.jar
mcw-lights-1.0.6-mc1.19.2fabric.jar
mcw-paintings-1.0.4fabric-mc1.19.2.jar
mcw-paths-1.0.3fabric-mc1.19.2.jar
mcw-roofs-2.2.4b-mc1.19.2fabric.jar
mcw-trapdoors-1.1.1-mc1.19.2fabric.jar
mcw-windows-2.1.2-mc1.19.2fabric.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
modmenu-4.2.0-beta.2.jar
moonlight-1.19.2-2.2.44-fabric.jar
moreculling-1.19.1-0.17.0.jar
Mosaics-Fabric-1.0.3.jar
mousewheelie-1.11.1+mc1.19.2.jar
MusicClient-mc1.19.2-1.0.0.jar
netherportalfix-fabric-1.19-10.0.1.jar
norecipebook-2.3+1.19.4.jar
Noteable-1.19.2-1.2.1.jar
notenoughanimations-fabric-1.6.2-mc1.19.2.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4.jar"
ok_zoomer-5.0.0-beta.9+1.19.jar
OpenSimpleFrames-1.0.8.jar
Origins-1.19.2-1.7.1.jar
origins-minus-2.0.6.jar
owo-lib-0.9.3+1.19.jar
paladin-furniture-mod-1.1.1-fabric-mc1.19.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.7.8+1.14.4-1.20.1.jar
pettable-1.3.1.jar
picohud-1.4.0+1.19.jar
portable-crafting-standalone-1.3.2+1.19.jar
PresenceFootsteps-1.6.4.jar
projectsavethepets-3.2.0+2022.e000b2a529.quilt.jar
QDResLoader-2.0.jar
qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar
quilt-kotlin-libraries-1.0.2+kt.1.8.0+flk.1.9.0.jar
quilt_loading_screen-4.0.0+1.19.jar
reacharound+1.19-1.1.2.jar
RebornCore-5.4.0.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
right-click-harvest-3.2.2+1.19.x-1.20-fabric.jar
simple_durability_tooltip-2.0.0.jar
simplefog-1.3.1.jar
skiptransitions-1.3.2+1.18.x.jar
SnowRealMagic-1.19.2-fabric-5.1.1.jar
snow-under-trees-fabric-1.0.0+1.19.2.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
starlight-1.1.1+fabric.ae22326.jar
statuseffecttimer-1.1.1+1.19.jar
styled-chat-2.0.3+1.19.2.jar
styled-nicknames-1.1.2+1.19.jar
styledplayerlist-2.2.2+1.19.1.jar
supermartijn642corelib-1.1.12-fabric-mc1.19.2.jar
supplementaries-1.19.2-2.3.20-fabric.jar
switchy-2.1.3+1.19.jar
switchy-inventories-1.5.4+1.19.jar
switchykit-1.2.0.jar
switchy-proxy-1.2.1+1.19.jar
switchy-resource-packs-1.1.3+1.19.jar
switchy-teleport-1.2.1+1.19.2.jar
TaxFreeLevels-1.3.3-fabric-1.19.jar
TechReborn-5.4.0.jar
TerraBlender-fabric-1.19.2-2.0.1.166.jar
textile_backup-2.5.0-1.19.jar
tinkerers_smithing-2.2.3+1.19.jar
tinkerers-statures-1.0.1.jar
toms_storage_fabric-1.19-1.5.9.jar
tooltipfix-1.1.1-1.19.jar
totem_anywhere_standalone-1.1.1+1.19.2.jar
trinkets-3.4.2.jar
twilightforest-fabric-1.19.2-4.2.357.jar
vehiclefix-3.4.jar
visuality-0.5.6.jar
voicechat-fabric-1.19.2-2.4.18.jar
wired-redstone-0.4.19+1.19.2.jar
wthit-plugins-1.0.6+1.19.jar
wthit-quilt-5.16.1.jar
yosbr-0.1.1.jar
youre-in-grave-danger-1.4.9.jar

**Comment by woodiertexas** [comment]
Since we do not support old Arch-Ex versions, here are some options to rectify the issue:

- Use the [HexxyCraft](https://github.com/HexxyCraft/architecture-extensions) fork of Arch-Ex which fixes the issue in Arch-Ex 1
- Upgrade to [Arch-Ex 2.1.0](https://modrinth.com/mod/arch-ex/version/2.1.0+1.19) if you can upgrade to 1.19.4

**Comment by texaswriter** [comment]
Okay, thanks for the response. i tried that mod out and it fixes the issue.
