### ISSUE TITLE
Soul Ice 😳 

### ISSUE THREAD

**Issue by Siuolplex** [woodiertexas/architecture-extensions#6]
### List the blocks you want added to AE.

- Soul Ice
- Lightstone
- Dyed Planks

### What blocktypes do your block(s) fall under if applicable.

- [X] Column Block
- [X] Arch Block
- [X] Post Block
- [X] Beam Block

### Additional context

:)

**Comment by woodiertexas** [comment]
Soul Ice and Lightstone are pretty doable, as for the dyed planks... not so much... for now that is.

**Comment by woodiertexas** [comment]
Column and Post blocks for Soul Ice are done in https://github.com/woodiertexas/architecture-extensions/commit/028a4d8345b8fbea6ae4ab8cfc0c483d22bafb57

**Comment by woodiertexas** [comment]
Since Arch-Ex 2 is released. It is possible to do mod compat via its API which is documented here: https://github.com/DebuggyTeam/architecture-extensions/wiki/Integrating-Arch-Ex-into-your-mod
